import os
import logging
from fpdf import FPDF
from .base import BaseStage
from ..config import Config

logger = logging.getLogger(__name__)

class PDFReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(100, 116, 139)
        self.cell(0, 8, 'Teacher Knowledge Package (TKP) | Generated by AI Platform', 0, 1, 'R')
        self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}}', 0, 0, 'C')

class PublishingStage(BaseStage):
    """
    Stage 10: Formatting, PDF Document Generation and Packaging.
    """
    def execute(self, state: dict) -> dict:
        job_id = self.job_id
        output_dir = Config.OUTPUT_FOLDER
        os.makedirs(output_dir, exist_ok=True)
        pdf_path = os.path.join(output_dir, f"TKP_{job_id}.pdf")
        
        try:
            self._generate_pdf(state, pdf_path)
            logger.info(f"Generated PDF export at: {pdf_path}")
        except Exception as e:
            logger.error(f"Error compiling PDF: {e}")
            pdf_path = None

        return {
            "format": "JSON+PDF",
            "version": "1.0.0",
            "pdf_path": pdf_path,
            "ready_for_export": True
        }

    def _generate_pdf(self, state: dict, out_path: str):
        pdf = PDFReport()
        pdf.alias_nb_pages()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        classification = state.get("classification", {})
        knowledge = state.get("knowledge", {})
        lesson_plan = state.get("lesson_plan", {})
        period_contents = state.get("period_contents", [])
        activities = state.get("activities", [])
        assessments = state.get("ab_test_assessment", {})
        gaps = state.get("gap_analysis", {})

        subject = classification.get("subject", "General Curriculum")
        topic = classification.get("topic", "Teacher Knowledge Package")
        grade = classification.get("grade_level", "K-12")

        # Title Block
        pdf.set_font('Helvetica', 'B', 20)
        pdf.set_text_color(30, 58, 138)
        pdf.cell(0, 12, f"{subject}: {topic}", 0, 1, 'L')

        pdf.set_font('Helvetica', '', 11)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(0, 6, f"Target Grade: Grade {grade}  |  Board: CBSE/NCERT  |  Total Periods: {len(period_contents) or 3}", 0, 1, 'L')
        pdf.ln(4)

        def add_section_header(title):
            pdf.set_font('Helvetica', 'B', 14)
            pdf.set_text_color(15, 23, 42)
            pdf.cell(0, 9, title, 0, 1, 'L')
            pdf.set_draw_color(56, 189, 248)
            pdf.set_line_width(0.5)
            pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
            pdf.ln(3)

        # 1. Objectives & Concepts
        add_section_header("1. Core Learning Objectives & Key Concepts")
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(30, 41, 59)
        
        objs = knowledge.get("learning_objectives", [])
        if objs:
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(0, 6, "Learning Objectives:", 0, 1, 'L')
            pdf.set_font('Helvetica', '', 9.5)
            for o in objs[:5]:
                text = o if isinstance(o, str) else o.get("objective", str(o))
                pdf.multi_cell(0, 5, f"  * {text}")
            pdf.ln(2)

        concepts = knowledge.get("concepts", [])
        if concepts:
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(0, 6, "Key Concepts & Definitions:", 0, 1, 'L')
            pdf.set_font('Helvetica', '', 9.5)
            for c in concepts[:6]:
                name = c if isinstance(c, str) else c.get("name", "")
                defn = "" if isinstance(c, str) else c.get("definition", "")
                pdf.multi_cell(0, 5, f"  * {name}: {defn}")
            pdf.ln(4)

        # 2. Lesson Breakdown
        add_section_header("2. Multi-Period Lesson Plan Schedule")
        periods = lesson_plan.get("periods", [])
        for p in periods:
            p_num = p.get("period_number", 1)
            p_title = p.get("title", f"Period {p_num}")
            p_dur = p.get("duration_minutes", 45)
            pdf.set_font('Helvetica', 'B', 10.5)
            pdf.set_text_color(30, 58, 138)
            pdf.cell(0, 6, f"Period {p_num}: {p_title} ({p_dur} mins)", 0, 1, 'L')
            pdf.set_font('Helvetica', '', 9.5)
            pdf.set_text_color(51, 65, 85)
            pdf.multi_cell(0, 5, f"Methodology: {p.get('teaching_methodology', 'Interactive lecture')}")
            pdf.multi_cell(0, 5, f"Key Takeaway: {p.get('key_takeaway', '')}")
            pdf.ln(2)

        # 3. Teacher Scripts & Blackboard Notes
        if period_contents:
            add_section_header("3. Teacher Delivery Scripts & Blackboard Notes")
            for pc in period_contents:
                p_num = pc.get("period_number", 1)
                pdf.set_font('Helvetica', 'B', 10.5)
                pdf.set_text_color(15, 23, 42)
                pdf.cell(0, 6, f"Period {p_num} Teacher Script:", 0, 1, 'L')
                pdf.set_font('Helvetica', '', 9)
                pdf.set_text_color(51, 65, 85)
                script = pc.get("teacher_script", "")
                pdf.multi_cell(0, 4.5, script[:800] + ("..." if len(script) > 800 else ""))
                pdf.ln(1)
                
                bb = pc.get("blackboard_notes", "")
                if bb:
                    pdf.set_font('Helvetica', 'B', 9)
                    pdf.cell(0, 5, "Blackboard Outline:", 0, 1, 'L')
                    pdf.set_font('Courier', '', 8.5)
                    pdf.multi_cell(0, 4, str(bb))
                pdf.ln(3)

        # 4. Activities
        if activities:
            add_section_header("4. Classroom Activities")
            for act in activities:
                title = act.get("title") or act.get("activity_name", "In-Class Exercise")
                pdf.set_font('Helvetica', 'B', 10)
                pdf.set_text_color(30, 58, 138)
                pdf.cell(0, 6, f"* {title} ({act.get('duration_minutes', 15)} mins)", 0, 1, 'L')
                pdf.set_font('Helvetica', '', 9)
                pdf.set_text_color(51, 65, 85)
                pdf.multi_cell(0, 4.5, f"Instructions: {act.get('instructions', act.get('description', ''))}")
                pdf.ln(2)

        # 5. Assessments (A/B Test)
        add_section_header("5. Differentiated A/B Test Assessments")
        var_a = assessments.get("variant_a", {})
        var_b = assessments.get("variant_b", {})
        
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 6, "Variant A (Standard / Baseline Assessment):", 0, 1, 'L')
        pdf.set_font('Helvetica', '', 9)
        for i, q in enumerate(var_a.get("questions", [])[:4]):
            pdf.multi_cell(0, 4.5, f"Q{i+1}: {q.get('question', q.get('text', ''))}")
            pdf.set_text_color(16, 185, 129)
            pdf.multi_cell(0, 4.5, f"Ans: {q.get('correct_answer', q.get('answer', ''))}")
            pdf.set_text_color(51, 65, 85)
        pdf.ln(2)

        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 6, "Variant B (Higher-Order Thinking / Deep Reasoning):", 0, 1, 'L')
        pdf.set_font('Helvetica', '', 9)
        for i, q in enumerate(var_b.get("questions", [])[:4]):
            pdf.multi_cell(0, 4.5, f"Q{i+1}: {q.get('question', q.get('text', ''))}")
            pdf.set_text_color(16, 185, 129)
            pdf.multi_cell(0, 4.5, f"Ans: {q.get('correct_answer', q.get('answer', ''))}")
            pdf.set_text_color(51, 65, 85)
        pdf.ln(3)

        # 6. Misconceptions
        misconceptions = gaps.get("misconceptions", [])
        if misconceptions:
            add_section_header("6. Misconception Diagnostics & Remedial Action")
            for m in misconceptions[:4]:
                m_text = m if isinstance(m, str) else m.get("misconception", "")
                diag = "" if isinstance(m, str) else m.get("diagnostic_question", "")
                remedy = "" if isinstance(m, str) else m.get("remedial_strategy", "")
                pdf.set_font('Helvetica', 'B', 9.5)
                pdf.set_text_color(220, 38, 38)
                pdf.cell(0, 5, f"Misconception: {m_text}", 0, 1, 'L')
                pdf.set_font('Helvetica', '', 9)
                pdf.set_text_color(51, 65, 85)
                if diag: pdf.multi_cell(0, 4.5, f"Diagnostic Check: {diag}")
                if remedy: pdf.multi_cell(0, 4.5, f"Remedial Strategy: {remedy}")
                pdf.ln(2)

        pdf.output(out_path)
